import { MofEntry } from './types';

export const TOPOLOGIES = ['pcu', 'fcu', 'tbo', 'mtn', 'sod', 'csq', 'nbo', 'bcu', 'loi', 'she', 'rht', 'acs', 'the'];
export const METALS = ['Zn', 'Zr', 'Cu', 'Cr', 'Al', 'Mg', 'Co', 'Ni', 'Fe', 'Mn', 'V'];

export const MOCK_MOF_DATA: MofEntry[] = [
  {
    doi: "10.1038/nature00000",
    mof_name: "MOF-5",
    mof_description: "Canonical zinc-carboxylate MOF consisting of Zn4O clusters linked by 1,4-benzenedicarboxylate. Prototypical pcu topology.",
    metal_1: "Zinc Nitrate Tetrahydrate",
    metal_1_abbr: "Zn",
    linker_1: "1,4-benzenedicarboxylic acid",
    linker_1_abbr: "H2BDC",
    topology_code: "pcu",
    solvent_main: "DEF",
    temperature_c: 105,
    time_h: 20,
    yield_percent: 88,
    bet_surface_area_m2g: 3500,
    pore_diameter_A: 12.9,
    tga_decomposition_temp_c: 400,
    water_stable: false,
    air_stable: false,
    crystal_morphology: "Cubic blocks",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "Zn(NO3)2·4H2O (0.80 g) and H2BDC (0.20 g) were dissolved in diethylformamide (DEF, 20 mL) in a glass jar. The vessel was tightly capped and heated in a convection oven at 105 °C for 20 hours. Clear cubic crystals formed on the walls and bottom of the jar.",
    activation_procedure: "The crystals were washed with DMF (3x10 mL) and chloroform (3x10 mL). The solvent was exchanged with fresh chloroform every 24h for 3 days. Finally, the sample was evacuated at room temperature for 12h, then at 120°C for 12h under dynamic vacuum.",
    ai_metrics: { synthesizability: 95, water_stability_score: 15, thermal_stability_score: 85 }
  },
  {
    doi: "10.1126/science.1039682",
    mof_name: "HKUST-1",
    mof_description: "Cu-paddlewheel based framework (Cu3(BTC)2) with 3D channels. Widely used for gas separation and catalysis.",
    metal_1: "Copper(II) Nitrate Trihydrate",
    metal_1_abbr: "Cu",
    linker_1: "1,3,5-benzenetricarboxylic acid",
    linker_1_abbr: "H3BTC",
    topology_code: "tbo",
    solvent_main: "Ethanol/Water (1:1)",
    temperature_c: 85,
    time_h: 24,
    yield_percent: 92,
    bet_surface_area_m2g: 1500,
    pore_diameter_A: 9.0,
    tga_decomposition_temp_c: 240,
    water_stable: false,
    air_stable: true,
    crystal_morphology: "Blue octahedra",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "Cu(NO3)2·3H2O (1.8 g) and H3BTC (0.85 g) were dissolved in a mixture of ethanol (25 mL) and deionized water (25 mL). The solution was stirred for 30 min, then transferred to a Teflon-lined autoclave and heated at 85 °C for 24 hours. A blue powder precipitated.",
    activation_procedure: "The blue precipitate was filtered and washed with water/ethanol. Solvent exchange was performed with pure ethanol for 3 days. The sample was activated under vacuum at 110 °C for 12 hours.",
    ai_metrics: { synthesizability: 98, water_stability_score: 30, thermal_stability_score: 60 }
  },
  {
    doi: "10.1021/ja8057953",
    mof_name: "UiO-66",
    mof_description: "Extremely robust Zr-MOF built from Zr6O4(OH)4 clusters and BDC. Resistant to water, acid, and high temperatures.",
    metal_1: "Zirconium(IV) Chloride",
    metal_1_abbr: "Zr",
    linker_1: "1,4-benzenedicarboxylic acid",
    linker_1_abbr: "H2BDC",
    topology_code: "fcu",
    solvent_main: "DMF",
    temperature_c: 120,
    time_h: 24,
    yield_percent: 96,
    bet_surface_area_m2g: 1180,
    pore_diameter_A: 6.0,
    tga_decomposition_temp_c: 540,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Microcrystalline octahedra",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "ZrCl4 (0.53 g) and H2BDC (0.34 g) were dissolved in DMF (30 mL) with 1 mL of acetic acid as modulator. The mixture was placed in a 100 mL Teflon-lined autoclave and heated at 120 °C for 24 hours.",
    activation_procedure: "The white powder was centrifuged and washed with DMF (3x) and methanol (3x). The sample was then dried at 80 °C and finally activated at 200 °C under dynamic vacuum for 12 hours.",
    ai_metrics: { synthesizability: 92, water_stability_score: 99, thermal_stability_score: 98 }
  },
  {
    doi: "10.1126/science.1110462",
    mof_name: "MIL-101(Cr)",
    mof_description: "Giant pore Cr-MOF with mtn zeotypic topology. Features mesoporous cages of 29Å and 34Å.",
    metal_1: "Chromium(III) Nitrate Nonahydrate",
    metal_1_abbr: "Cr",
    linker_1: "1,4-benzenedicarboxylic acid",
    linker_1_abbr: "H2BDC",
    topology_code: "mtn",
    solvent_main: "Water",
    temperature_c: 220,
    time_h: 8,
    yield_percent: 50,
    bet_surface_area_m2g: 4100,
    pore_diameter_A: 29.0,
    tga_decomposition_temp_c: 275,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Green powder",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "Cr(NO3)3·9H2O (2.0 g), H2BDC (0.83 g), and HF (0.2 mL) were added to H2O (25 mL). The mixture was heated in an autoclave at 220 °C for 8 hours. After cooling, the mixture was filtered to remove unreacted acid (recrystallized).",
    activation_procedure: "The green powder was washed with hot ethanol and water. To remove pore-trapped acid, the solid was treated with solvothermal ethanol at 80 °C for 24h, then dried and activated at 150 °C under vacuum.",
    ai_metrics: { synthesizability: 65, water_stability_score: 95, thermal_stability_score: 75 }
  },
  {
    doi: "10.1073/pnas.0602439103",
    mof_name: "ZIF-8",
    mof_description: "Zeolitic Imidazolate Framework with sodalite topology. Hydrophobic and chemically stable.",
    metal_1: "Zinc Nitrate Hexahydrate",
    metal_1_abbr: "Zn",
    linker_1: "2-methylimidazole",
    linker_1_abbr: "H-MeIM",
    topology_code: "sod",
    solvent_main: "Methanol",
    temperature_c: 25,
    time_h: 1,
    yield_percent: 98,
    bet_surface_area_m2g: 1630,
    pore_diameter_A: 11.6,
    tga_decomposition_temp_c: 420,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Rhombic dodecahedra",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "A solution of Zn(NO3)2·6H2O (1.17 g) in methanol (40 mL) was rapidly poured into a solution of 2-methylimidazole (2.60 g) in methanol (40 mL). The mixture turned turbid immediately and was stirred at room temperature for 1 hour.",
    activation_procedure: "The product was collected by centrifugation, washed with fresh methanol three times, and dried at room temperature. Activation was performed at 150 °C under vacuum for 6 hours.",
    ai_metrics: { synthesizability: 99, water_stability_score: 90, thermal_stability_score: 88 }
  },
  {
    doi: "10.1021/ja400365y",
    mof_name: "MOF-808",
    mof_description: "Zr6 cluster based MOF with spn topology. Large pores ideal for peptide hydrolysis catalysis.",
    metal_1: "Zirconium Oxychloride Octahydrate",
    metal_1_abbr: "Zr",
    linker_1: "1,3,5-benzenetricarboxylic acid",
    linker_1_abbr: "H3BTC",
    topology_code: "spn",
    solvent_main: "DMF/Formic Acid",
    temperature_c: 100,
    time_h: 48,
    yield_percent: 72,
    bet_surface_area_m2g: 2050,
    pore_diameter_A: 18.4,
    tga_decomposition_temp_c: 510,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Block crystals",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "ZrOCl2·8H2O (0.97 g) and H3BTC (0.21 g) were dissolved in a mixture of DMF (20 mL) and Formic Acid (20 mL). The solution was heated in a sealed glass vial at 100 °C for 48 hours.",
    activation_procedure: "The crystals were washed with DMF (3x) and acetone (3x) over 3 days. The sample was activated by heating at 150 °C under dynamic vacuum for 24 hours.",
    ai_metrics: { synthesizability: 85, water_stability_score: 96, thermal_stability_score: 95 }
  },
  {
    doi: "10.1021/cm050000",
    mof_name: "MOF-74(Ni)",
    mof_description: "One-dimensional hexagonal channels with high density of open metal sites. Excellent for CO2 capture.",
    metal_1: "Nickel(II) Nitrate Hexahydrate",
    metal_1_abbr: "Ni",
    linker_1: "2,5-dihydroxyterephthalic acid",
    linker_1_abbr: "H4DOBDC",
    topology_code: "bcu", 
    solvent_main: "DMF/Ethanol/Water",
    temperature_c: 110,
    time_h: 72,
    yield_percent: 68,
    bet_surface_area_m2g: 1350,
    pore_diameter_A: 11.0,
    tga_decomposition_temp_c: 380,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Yellow-green needles",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "Ni(NO3)2·6H2O (0.73 g) and H4DOBDC (0.25 g) were dissolved in DMF/Ethanol/Water (1:1:1 v/v, 60 mL total). The mixture was sonicated and then heated at 110 °C for 72 hours in a Teflon-lined autoclave.",
    activation_procedure: "The needle-like crystals were washed with DMF, then the solvent was exchanged with methanol (4x per day for 3 days). Activation required heating at 200 °C under vacuum for 12 hours to fully remove coordinated solvent.",
    ai_metrics: { synthesizability: 80, water_stability_score: 85, thermal_stability_score: 70 }
  },
  {
    doi: "10.1038/nmat3827",
    mof_name: "NU-1000",
    mof_description: "Mesoporous Zr-MOF with csq topology derived from PE-type SBU. Suitable for enzyme immobilization.",
    metal_1: "Zirconium Oxychloride",
    metal_1_abbr: "Zr",
    linker_1: "1,3,6,8-tetrakis(p-benzoic acid)pyrene",
    linker_1_abbr: "H4TBAPy",
    topology_code: "csq",
    solvent_main: "DEF/Benzoic Acid",
    temperature_c: 100,
    time_h: 48,
    yield_percent: 60,
    bet_surface_area_m2g: 2320,
    pore_diameter_A: 31.0,
    tga_decomposition_temp_c: 500,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Yellow rods",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "ZrOCl2·8H2O (97 mg), Benzoic acid (2.7 g), and H4TBAPy (40 mg) were dissolved in DEF (8 mL). The mixture was heated at 100 °C for 48 hours in a convection oven.",
    activation_procedure: "Washed with DMF, then treated with 8M HCl in DMF at 100 °C for 12h (to remove modulator). Solvent exchanged with acetone. Activated at 120 °C under vacuum.",
    ai_metrics: { synthesizability: 70, water_stability_score: 92, thermal_stability_score: 94 }
  },
  {
    doi: "10.1002/anie.201204152",
    mof_name: "PCN-222",
    mof_description: "Porphyrin-based Zr-MOF with large 1D channels. Photoactive and biomimetic catalytic activity.",
    metal_1: "Zirconium(IV) Chloride",
    metal_1_abbr: "Zr",
    linker_1: "Tetrakis(4-carboxyphenyl)porphyrin",
    linker_1_abbr: "H2TCPP",
    topology_code: "csq",
    solvent_main: "DMF/Propionic Acid",
    temperature_c: 120,
    time_h: 16,
    yield_percent: 82,
    bet_surface_area_m2g: 2200,
    pore_diameter_A: 32.0,
    tga_decomposition_temp_c: 450,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Dark red needles",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "ZrCl4 (50 mg), H2TCPP (30 mg), and benzoic acid (0.5 g) were dissolved in DMF (10 mL). Heated at 120 °C for 16h. Dark red needle-shaped crystals were obtained.",
    activation_procedure: "Washed with DMF and acetone. Solvent exchanged with acetone 3x. Dried in air, then activated at 100 °C under vacuum.",
    ai_metrics: { synthesizability: 78, water_stability_score: 88, thermal_stability_score: 90 }
  },
  {
    doi: "10.1038/nmat1668",
    mof_name: "NOTT-101",
    mof_description: "Copper carboxylate MOF designed for high capacity hydrogen storage via open metal sites.",
    metal_1: "Copper(II) Nitrate",
    metal_1_abbr: "Cu",
    linker_1: "Terphenyl tetracarboxylic acid",
    linker_1_abbr: "H4L",
    topology_code: "nbo",
    solvent_main: "DMF/Dioxane",
    temperature_c: 80,
    time_h: 24,
    yield_percent: 75,
    bet_surface_area_m2g: 2805,
    pore_diameter_A: 10.5,
    tga_decomposition_temp_c: 290,
    water_stable: false,
    air_stable: true,
    crystal_morphology: "Blue plates",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "Cu(NO3)2·2.5H2O and the organic linker H4L were suspended in DMF/Dioxane/H2O with HCl added. Heated at 80 °C for 24h.",
    activation_procedure: "Acetone exchange followed by activation at 100 °C under high vacuum.",
    ai_metrics: { synthesizability: 85, water_stability_score: 10, thermal_stability_score: 40 }
  },
  {
    doi: "10.1039/c4ta03210k",
    mof_name: "AI-Fum (MIL-53-Al)",
    mof_description: "Aluminum fumarate MOF. Highly scalable, water stable, and used in adsorption cooling.",
    metal_1: "Aluminum Chloride Hexahydrate",
    metal_1_abbr: "Al",
    linker_1: "Fumaric Acid",
    linker_1_abbr: "H2Fum",
    topology_code: "loi",
    solvent_main: "Water",
    temperature_c: 60,
    time_h: 4,
    yield_percent: 96,
    bet_surface_area_m2g: 1100,
    pore_diameter_A: 5.8,
    tga_decomposition_temp_c: 450,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "White microcrystals",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "AlCl3·6H2O (2.4 g) and Fumaric acid (1.16 g) dissolved in water (20 mL). Heated under reflux at 60 °C for 4 hours. A white solid precipitated immediately.",
    activation_procedure: "Washed with water and ethanol. Activated by heating at 150 °C in air for 12 hours.",
    ai_metrics: { synthesizability: 99, water_stability_score: 100, thermal_stability_score: 90 }
  },
  {
    doi: "10.1021/ic202136x",
    mof_name: "Mg-MOF-74",
    mof_description: "Magnesium variant of MOF-74. Record holder for low-pressure CO2 capture.",
    metal_1: "Magnesium Nitrate Hexahydrate",
    metal_1_abbr: "Mg",
    linker_1: "2,5-dihydroxyterephthalic acid",
    linker_1_abbr: "H4DOBDC",
    topology_code: "bcu",
    solvent_main: "DMF/Ethanol/Water",
    temperature_c: 125,
    time_h: 24,
    yield_percent: 88,
    bet_surface_area_m2g: 1800,
    pore_diameter_A: 12.0,
    tga_decomposition_temp_c: 400,
    water_stable: false,
    air_stable: true,
    crystal_morphology: "Yellow needles",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "Mg(NO3)2·6H2O (0.48 g) and H4DOBDC (0.11 g) in DMF/Ethanol/Water (15:1:1). Heated at 125 °C for 24 hours.",
    activation_procedure: "Extensive methanol exchange (5x daily for 4 days) is required to remove heavy DMF molecules. Activated at 250 °C under high vacuum.",
    ai_metrics: { synthesizability: 82, water_stability_score: 45, thermal_stability_score: 80 }
  },
   {
    doi: "10.1126/science.1067208",
    mof_name: "IRMOF-3",
    mof_description: "Amino-functionalized derivative of MOF-5 (isoreticular). -NH2 groups available for post-synthetic modification.",
    metal_1: "Zinc Nitrate Tetrahydrate",
    metal_1_abbr: "Zn",
    linker_1: "2-aminoterephthalic acid",
    linker_1_abbr: "H2BDC-NH2",
    topology_code: "pcu",
    solvent_main: "DEF",
    temperature_c: 105,
    time_h: 24,
    yield_percent: 80,
    bet_surface_area_m2g: 2400,
    pore_diameter_A: 12.2,
    tga_decomposition_temp_c: 350,
    water_stable: false,
    air_stable: false,
    crystal_morphology: "Orange cubes",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "Zn(NO3)2·4H2O and 2-aminoterephthalic acid dissolved in DEF. Heated at 105 °C for 24 hours.",
    activation_procedure: "Chloroform exchange followed by mild activation at room temperature vacuum, then 100 °C.",
    ai_metrics: { synthesizability: 90, water_stability_score: 12, thermal_stability_score: 70 }
  },
  {
    doi: "10.1021/cm3037267",
    mof_name: "CAU-10-H",
    mof_description: "Aluminum isophthalate MOF with helical channels. Extremely stable and suitable for heat pumps.",
    metal_1: "Aluminum Sulfate",
    metal_1_abbr: "Al",
    linker_1: "Isophthalic acid",
    linker_1_abbr: "H2IPA",
    topology_code: "she",
    solvent_main: "Water/DMF",
    temperature_c: 100,
    time_h: 12,
    yield_percent: 90,
    bet_surface_area_m2g: 635,
    pore_diameter_A: 5.0,
    tga_decomposition_temp_c: 450,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "White powder",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "Al2(SO4)3·18H2O and isophthalic acid in DMF/Water. Heated at 100 °C for 12 hours.",
    activation_procedure: "Washed with water. Heated at 120 °C in air to activate.",
    ai_metrics: { synthesizability: 96, water_stability_score: 98, thermal_stability_score: 95 }
  },
  {
    doi: "10.1021/cg200506k",
    mof_name: "UiO-67",
    mof_description: "Extended version of UiO-66 using BPDC linker. Larger pores but less hydrothermally stable than UiO-66.",
    metal_1: "Zirconium(IV) Chloride",
    metal_1_abbr: "Zr",
    linker_1: "Biphenyl-4,4'-dicarboxylic acid",
    linker_1_abbr: "H2BPDC",
    topology_code: "fcu",
    solvent_main: "DMF",
    temperature_c: 120,
    time_h: 24,
    yield_percent: 85,
    bet_surface_area_m2g: 2500,
    pore_diameter_A: 12.0,
    tga_decomposition_temp_c: 500,
    water_stable: true,
    air_stable: true,
    crystal_morphology: "Octahedra",
    crystal_form: "Powder",
    status: "ok",
    synthesis_procedure: "ZrCl4 and H2BPDC dissolved in DMF with HCl/Benzoic acid modulator. Heated at 120 °C for 24h.",
    activation_procedure: "Acetone exchange, dried at 80 °C. Activated at 150 °C under vacuum.",
    ai_metrics: { synthesizability: 88, water_stability_score: 75, thermal_stability_score: 92 }
  },
  {
    doi: "10.1126/science.1099392",
    mof_name: "MOF-177",
    mof_description: "High surface area zinc MOF constructed from BTB linker. Record holder for surface area at time of discovery.",
    metal_1: "Zinc Nitrate Tetrahydrate",
    metal_1_abbr: "Zn",
    linker_1: "1,3,5-benzenetribenzoate",
    linker_1_abbr: "H3BTB",
    topology_code: "qom", 
    solvent_main: "DEF",
    temperature_c: 100,
    time_h: 23,
    yield_percent: 70,
    bet_surface_area_m2g: 4500,
    pore_diameter_A: 11.0, 
    tga_decomposition_temp_c: 350,
    water_stable: false,
    air_stable: true,
    crystal_morphology: "Block",
    crystal_form: "Single Crystal",
    status: "ok",
    synthesis_procedure: "Zn(NO3)2·4H2O and H3BTB in DEF. Heated at 100 °C for 23 hours.",
    activation_procedure: "Chloroform exchange. Careful activation/drying required to prevent pore collapse.",
    ai_metrics: { synthesizability: 60, water_stability_score: 10, thermal_stability_score: 50 }
  }
];